name: news_user_app
description: "Flutter User App for reading published news."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase core (required to initialize Firebase)
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0

  # Firestore (to fetch news & categories)
  cloud_firestore: ^5.0.0

  # For date/time formatting
  intl: ^0.19.0

  # For icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
